name: bigtop-select rpm build

on:
  push:
    branches:
      - master-arg
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      - name: Build and deploy rpm
        uses: VladimirBogomolov/bigtop-su@9ccf6ca819730e656b227c4b62507547c3aa1a29
        with:
          package-name: 'bigtop-select'
          stack-name: 'dla'
          repo-dir: ${{ vars.REPO_DIR }}
